# Generated by Django 6.0.3 on 2026-05-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('INGENIEUR_RESEAUX', 'Ingénieur Réseaux'), ('AGENT_CALL_CENTER', 'Agent Call Center'), ('RESPONSABLE_REPORTING', 'Responsable Reporting')], default='AGENT_CALL_CENTER', max_length=30, verbose_name='role_user'),
        ),
    ]
