# Generated by Django 6.0.3 on 2026-06-26 14:21

import re
from django.db import migrations, models


def assign_code_and_fix_emails(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for idx, user in enumerate(CustomUser.objects.all().order_by('id')):
        code = f'U{str(idx + 1).zfill(3)}'
        user.code_user = code
        user.username = code
        if not user.email:
            user.email = f'{code.lower()}@djezzy.dz'
        user.save(update_fields=['code_user', 'username', 'email'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_phone_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_user',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True, verbose_name='Code utilisateur'),
        ),
        migrations.RunPython(assign_code_and_fix_emails, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
