# Generated by Django 6.0.6 on 2026-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('INGENIEUR_RESEAUX', 'Ingénieur Réseaux'), ('AGENT_CALL_CENTER', 'Agent Call Center'), ('RESPONSABLE_REPORTING', 'Responsable Reporting'), ('SUPERVISEUR', 'Superviseur')], default='AGENT_CALL_CENTER', max_length=30, verbose_name='role_user'),
        ),
    ]
