# Generated by Django 6.0.6 on 2026-07-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
