# Generated by Django 6.0.6 on 2026-07-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_must_change_password_delete_demandecompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Doit changer le mot de passe'),
        ),
    ]
