# Generated by Django 6.0.3 on 2026-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_reseau', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereseau',
            options={'ordering': ['wilaya', 'name'], 'verbose_name': 'Site Réseau', 'verbose_name_plural': 'Sites Réseau'},
        ),
        migrations.RemoveField(
            model_name='sitereseau',
            name='nom_site',
        ),
        migrations.RemoveField(
            model_name='sitereseau',
            name='technologie',
        ),
        migrations.AddField(
            model_name='sitereseau',
            name='commune',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitereseau',
            name='name',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitereseau',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitereseau',
            name='code_site',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sitereseau',
            name='wilaya',
            field=models.CharField(max_length=100),
        ),
    ]
