# reclamations/models.py
# ─────────────────────────────────────────────────────────────
# Ticket and comment models for the complaint management system.
# The GroupeTicket model represents a consolidated incident ticket
# visible to engineers, grouping multiple customer reclamations
# about the same issue at the same site.
# ─────────────────────────────────────────────────────────────
import re
from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator
from django.utils import timezone
from sites_reseau.models import SiteReseau


# ── Validators ───────────────────────────────────────────────
phone_validator = RegexValidator(
    regex=r'^0[5-7]\d{8}$',
    message='Le numéro doit être un numéro de téléphone valide (05/06/07 + 8 chiffres).',
)
name_validator = RegexValidator(
    regex=r'^[a-zA-Z\sàâéèêëïîôùûüÿçœæ\-]+$',
    message='Ce champ ne doit contenir que des lettres.',
)


# Priority numeric mapping for averaging
PRIORITE_SCORES = {
    'basse': 15,
    'normale': 45,
    'haute': 80,
    'critique': 120,
}

PRIORITE_FROM_SCORE = [
    (100, 'critique'),
    (60,  'haute'),
    (30,  'normale'),
    (0,   'basse'),
]


def score_to_priorite(score):
    for threshold, label in PRIORITE_FROM_SCORE:
        if score >= threshold:
            return label
    return 'basse'


class GroupeTicket(models.Model):
    """
    Consolidated ticket visible to network engineers. Groups multiple
    customer reclamations about the same issue at the same site.
    Title and description are AI-generated by Mistral.
    """

    STATUT_CHOICES = [
        ('ouvert',    'Ouvert'),
        ('resolu',    'Résolu'),
        ('ferme',     'Fermé'),
    ]

    PRIORITE_CHOICES = [
        ('basse',    'Basse'),
        ('normale',  'Normale'),
        ('haute',    'Haute'),
        ('critique', 'Critique'),
    ]

    numero_ticket = models.CharField(max_length=20, unique=True, editable=False)
    site = models.ForeignKey(
        SiteReseau,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='groupes_tickets',
        verbose_name='Site concerné',
    )
    titre = models.CharField(max_length=255, verbose_name='Titre du ticket')
    description = models.TextField(verbose_name='Description du problème', blank=True, default='')
    mots_cles = models.CharField(max_length=255, blank=True, default='', verbose_name='Mots-clés consolidés')
    priorite = models.CharField(max_length=10, choices=PRIORITE_CHOICES, default='normale')
    statut = models.CharField(max_length=10, choices=STATUT_CHOICES, default='ouvert')

    assigne_a = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='groupes_tickets_assignes',
        verbose_name='Assigné à',
    )
    cree_par = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='groupes_tickets_crees',
        verbose_name='Créé par',
    )

    nombre_reclamations = models.IntegerField(default=0)
    premier_signalement = models.DateTimeField(null=True, blank=True)

    is_archived = models.BooleanField(default=False)
    archived_at = models.DateTimeField(null=True, blank=True)
    archived_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='groupes_tickets_archives',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    resolu_le = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = 'Groupe Ticket'
        verbose_name_plural = 'Groupe Tickets'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.numero_ticket} — {self.titre}"

    def recalculer_priorite(self):
        reclamations = self.reclamations.all()
        if not reclamations:
            return
        total = 0
        for r in reclamations:
            total += PRIORITE_SCORES.get(r.priorite, 45)
        avg = total / reclamations.count()
        self.priorite = score_to_priorite(avg)

    def save(self, *args, **kwargs):
        if not self.numero_ticket:
            import re
            existing = GroupeTicket.objects.filter(
                numero_ticket__regex=r'^GT\d+$'
            ).values_list('numero_ticket', flat=True)
            max_num = 0
            for code in existing:
                try:
                    num = int(re.sub(r'\D', '', code))
                    if num > max_num:
                        max_num = num
                except ValueError:
                    continue
            self.numero_ticket = f'GT{str(max_num + 1).zfill(6)}'

        if self.statut == 'resolu' and not self.resolu_le:
            self.resolu_le = timezone.now()
        elif self.statut != 'resolu':
            self.resolu_le = None

        super().save(*args, **kwargs)


class Client(models.Model):
    """
    Represents a Djezzy customer. Each client is identified by
    their phone number (unique, starts with 05/06/07).
    """

    TYPE_CLIENT_CHOICES = [
        ('particulier', 'Particulier'),
        ('entreprise',  'Entreprise'),
    ]

    numero = models.CharField(
        max_length=20,
        unique=True,
        validators=[phone_validator],
        verbose_name='Numéro de téléphone',
    )
    prenom = models.CharField(
        max_length=200,
        validators=[name_validator],
        verbose_name='Prénom',
    )
    nom = models.CharField(
        max_length=200,
        validators=[name_validator],
        verbose_name='Nom',
    )
    type_client = models.CharField(
        max_length=12,
        choices=TYPE_CLIENT_CHOICES,
        default='particulier',
        verbose_name='Type de client',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.prenom} {self.nom} ({self.numero})"

    @property
    def nom_complet(self):
        return f"{self.prenom} {self.nom}"


class Reclamation(models.Model):
    """
    Individual customer complaint. Linked to a GroupeTicket which
    groups similar complaints about the same issue at the same site.
    """

    STATUT_CHOICES = [
        ('ouvert',    'Ouvert'),
        ('resolu',    'Résolu'),
        ('ferme',     'Fermé'),
    ]

    PRIORITE_CHOICES = [
        ('basse',    'Basse'),
        ('normale',  'Normale'),
        ('haute',    'Haute'),
        ('critique', 'Critique'),
    ]

    TYPE_CLIENT_CHOICES = [
        ('particulier', 'Particulier'),
        ('entreprise',  'Entreprise'),
    ]

    numero_ticket = models.CharField(max_length=20, unique=True, editable=False)

    client = models.ForeignKey(
        Client,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='reclamations',
        verbose_name='Client',
    )

    nom_client = models.CharField(max_length=200, verbose_name='Nom du client')
    telephone_client = models.CharField(max_length=20, verbose_name='Téléphone client')
    email_client = models.EmailField(verbose_name='Email client', blank=True, default='')
    type_client = models.CharField(
        max_length=12, choices=TYPE_CLIENT_CHOICES, default='particulier',
        verbose_name='Type de client',
    )

    site = models.ForeignKey(
        SiteReseau,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='reclamations',
        verbose_name='Site concerné',
    )

    groupe = models.ForeignKey(
        GroupeTicket,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='reclamations',
        verbose_name='Groupe ticket',
    )

    mots_cles_ia = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name="Mots-clés pour l'IA",
    )

    priorite = models.CharField(max_length=10, choices=PRIORITE_CHOICES, default='normale')
    statut = models.CharField(max_length=10, choices=STATUT_CHOICES, default='ferme')

    cree_par = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='reclamations_creees',
        verbose_name='Créé par',
    )
    assigne_a = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='reclamations_assignees',
        verbose_name='Assigné à',
    )

    is_archived = models.BooleanField(default=False, verbose_name='Archivé')
    archived_at = models.DateTimeField(null=True, blank=True)
    archived_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='reclamations_archivees',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    resolu_le = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = 'Réclamation'
        verbose_name_plural = 'Réclamations'
        ordering = ['-created_at']

    def __str__(self):
        return f"Ticket {self.numero_ticket} — {self.get_statut_display()}"

    @property
    def nom_complet_client(self):
        return self.nom_client

    def save(self, *args, **kwargs):
        if self.mots_cles_ia:
            from keywords_config import calculer_priorite
            self.priorite = calculer_priorite(self.mots_cles_ia)

        if not self.numero_ticket:
            existing = Reclamation.objects.filter(numero_ticket__regex=r'^R\d+$').values_list('numero_ticket', flat=True)
            max_num = 0
            for code in existing:
                try:
                    num = int(re.sub(r'\D', '', code))
                    if num > max_num:
                        max_num = num
                except ValueError:
                    continue
            self.numero_ticket = f'R{str(max_num + 1).zfill(4)}'

        if self.statut == 'resolu' and not self.resolu_le:
            self.resolu_le = timezone.now()
        elif self.statut != 'resolu':
            self.resolu_le = None

        super().save(*args, **kwargs)


class CommentaireTicket(models.Model):
    """
    Comments added by engineers on tickets. Used for internal
    communication about issue resolution progress.
    """
    reclamation = models.ForeignKey(
        Reclamation,
        on_delete=models.CASCADE,
        related_name='commentaires',
    )
    auteur = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
    )
    contenu = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f"Commentaire de {self.auteur} sur {self.reclamation}"
