# Generated by Django 6.0.3 on 2026-05-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='mots_cles_ia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Mots-clés pour l'IA"),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(blank=True, verbose_name="Description de l'incident"),
        ),
    ]
