# Generated by Django 6.0.3 on 2026-06-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamation_mots_cles_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='adresse_client',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse client'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='email_client',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email client'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='prenom_client',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Prénom du client'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='type_client',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=12, verbose_name='Type de client'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Description de l'incident"),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ferme', max_length=10),
        ),
    ]
