# Generated by Django 6.0.3 on 2026-06-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_reclamation_adresse_client_reclamation_email_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='adresse_client',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='prenom_client',
        ),
    ]
