# Generated by Django 6.0.6 on 2026-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0004_remove_reclamation_adresse_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ferme', max_length=10),
        ),
    ]
