# Generated by Django 6.0.6 on 2026-07-17 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0006_reclamation_archived_at_reclamation_archived_by_and_more'),
        ('sites_reseau', '0007_sitereseau_technologie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='description',
        ),
        migrations.CreateModel(
            name='GroupeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du ticket')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description du problème')),
                ('mots_cles', models.CharField(blank=True, default='', max_length=255, verbose_name='Mots-clés consolidés')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('nombre_reclamations', models.IntegerField(default=0)),
                ('premier_signalement', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolu_le', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_tickets_archives', to=settings.AUTH_USER_MODEL)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_tickets_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_tickets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_tickets', to='sites_reseau.sitereseau', verbose_name='Site concerné')),
            ],
            options={
                'verbose_name': 'Groupe Ticket',
                'verbose_name_plural': 'Groupe Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reclamation',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='reclamations.groupeticket', verbose_name='Groupe ticket'),
        ),
    ]
