# Generated by Django 6.0.6 on 2026-07-18 22:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0007_remove_reclamation_description_groupeticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être un numéro de téléphone valide (05/06/07 + 8 chiffres).', regex='^0[5-7]\\d{8}$')], verbose_name='Numéro de téléphone')),
                ('prenom', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Ce champ ne doit contenir que des lettres.', regex='^[a-zA-Z\\sàâéèêëïîôùûüÿçœæ\\-]+$')], verbose_name='Prénom')),
                ('nom', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Ce champ ne doit contenir que des lettres.', regex='^[a-zA-Z\\sàâéèêëïîôùûüÿçœæ\\-]+$')], verbose_name='Nom')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=12, verbose_name='Type de client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='groupeticket',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=10),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='reclamations.client', verbose_name='Client'),
        ),
    ]
