# Generated by Django 6.0.6 on 2026-07-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0008_client_alter_groupeticket_statut_reclamation_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeticket',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verrouillé le'),
        ),
        migrations.AddField(
            model_name='groupeticket',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_tickets_verrouilles', to=settings.AUTH_USER_MODEL, verbose_name='Verrouillé par'),
        ),
    ]
