# Generated by Django 6.0.6 on 2026-07-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0009_add_locked_fields_to_groupeticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentaireTicket',
        ),
    ]
