# Generated by Django 6.0.6 on 2026-06-28 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text="La demande saisie par l'utilisateur")),
                ('contenu', models.TextField(help_text="Contenu HTML généré par l'IA")),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport IA',
                'verbose_name_plural': 'Rapports IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
