# Generated by Django 6.0.6 on 2026-07-19 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, default='', max_length=10)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('user_role', models.CharField(blank=True, default='', max_length=30)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Connexion échouée'), ('create_ticket', 'Création réclamation'), ('update_ticket', 'Modification réclamation'), ('archive_ticket', 'Archivage réclamation'), ('restore_ticket', 'Restauration réclamation'), ('create_user', 'Création utilisateur'), ('update_user', 'Modification utilisateur'), ('archive_user', 'Archivage utilisateur'), ('toggle_user', 'Activation/Désactivation'), ('restore_user', 'Restauration utilisateur'), ('create_site', 'Création site'), ('update_site', 'Modification site'), ('archive_site', 'Archivage site'), ('restore_site', 'Restauration site'), ('toggle_site', 'Changement statut site'), ('generate_rapport', 'Génération rapport IA'), ('save_rapport', 'Sauvegarde rapport IA'), ('delete_rapport', 'Suppression rapport IA'), ('resolve_ticket', 'Résolution ticket'), ('assign_ticket', 'Assignation ticket')], db_index=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'action'], name='audit_log_a_created_45093c_idx'), models.Index(fields=['user', '-created_at'], name='audit_log_a_user_id_90fb03_idx')],
            },
        ),
    ]
