# Generated by Django 6.0.6 on 2026-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Connexion échouée'), ('create_ticket', 'Création réclamation'), ('update_ticket', 'Modification réclamation'), ('archive_ticket', 'Archivage réclamation'), ('restore_ticket', 'Restauration réclamation'), ('resolve_ticket', 'Résolution ticket'), ('assign_ticket', 'Assignation ticket'), ('create_user', 'Création utilisateur'), ('update_user', 'Modification utilisateur'), ('archive_user', 'Archivage utilisateur'), ('toggle_user', 'Activation/Désactivation'), ('restore_user', 'Restauration utilisateur'), ('delete_user', 'Suppression utilisateur'), ('reset_password', 'Réinitialisation mot de passe'), ('create_site', 'Création site'), ('update_site', 'Modification site'), ('archive_site', 'Archivage site'), ('restore_site', 'Restauration site'), ('delete_site', 'Suppression site'), ('toggle_site', 'Changement statut site'), ('generate_rapport', 'Génération rapport IA'), ('save_rapport', 'Sauvegarde rapport IA'), ('delete_rapport', 'Suppression rapport IA'), ('restore_rapport', 'Restauration rapport IA')], db_index=True, max_length=30),
        ),
    ]
