# Generated by Django 6.0.3 on 2026-03-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_site', models.CharField(max_length=50, unique=True, verbose_name='Code site')),
                ('nom_site', models.CharField(max_length=200, verbose_name='Nom du site')),
                ('technologie', models.CharField(choices=[('2G', '2G'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G')], default='4G', max_length=5)),
                ('wilaya', models.CharField(max_length=100, verbose_name='Wilaya')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('UP', 'UP — Opérationnel'), ('DOWN', 'DOWN — Hors service'), ('DEGRADE', 'Dégradé'), ('PERTURBE', 'Perturbé')], default='UP', max_length=10)),
                ('derniere_maj', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Réseau',
                'verbose_name_plural': 'Sites Réseau',
                'ordering': ['wilaya', 'nom_site'],
            },
        ),
    ]
