# Generated by Django 6.0.3 on 2026-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_reseau', '0002_alter_sitereseau_options_remove_sitereseau_nom_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereseau',
            options={'ordering': ['wilaya', 'nom'], 'verbose_name': 'Site Réseau', 'verbose_name_plural': 'Sites Réseau'},
        ),
        migrations.RenameField(
            model_name='sitereseau',
            old_name='name',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='sitereseau',
            name='code_site',
        ),
        migrations.RemoveField(
            model_name='sitereseau',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sitereseau',
            name='longitude',
        ),
        migrations.AddField(
            model_name='sitereseau',
            name='codeSite',
            field=models.CharField(default='TEMP', max_length=50, verbose_name='Code du Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitereseau',
            name='coordX',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitude (X)'),
        ),
        migrations.AddField(
            model_name='sitereseau',
            name='coordY',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitude (Y)'),
        ),
        migrations.AlterField(
            model_name='sitereseau',
            name='statut',
            field=models.CharField(choices=[('UP', 'Opérationnel'), ('DOWN', 'Hors service'), ('DEGRADE', 'Dégradé'), ('PERTURBE', 'Perturbé')], default='UP', max_length=10),
        ),
    ]
