# Generated by Django 6.0.3 on 2026-06-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_reseau', '0003_alter_sitereseau_options_rename_name_sitereseau_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereseau',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
