# Generated by Django 6.0.6 on 2026-06-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_reseau', '0004_sitereseau_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereseau',
            name='statut',
            field=models.CharField(choices=[('UP', 'Opérationnel'), ('DOWN', 'Hors service')], default='UP', max_length=10),
        ),
    ]
