# Generated by Django 6.0.6 on 2026-06-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_reseau', '0005_alter_sitereseau_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereseau',
            name='rayon_couverture',
            field=models.IntegerField(default=800, verbose_name='Rayon de couverture (m)'),
        ),
    ]
