# Generated by Django 6.0.6 on 2026-06-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_reseau', '0006_sitereseau_rayon_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereseau',
            name='technologie',
            field=models.CharField(choices=[('4G', '4G'), ('5G', '5G')], default='5G', max_length=2, verbose_name='Technologie'),
        ),
    ]
