# Generated by Django 6.0.6 on 2026-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_reseau', '0007_sitereseau_technologie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereseau',
            name='statut',
            field=models.CharField(choices=[('UP', 'Opérationnel'), ('DOWN', 'Hors service'), ('DEGRADE', 'Dégradé'), ('PERTURBE', 'Perturbé')], default='UP', max_length=10),
        ),
    ]
