# Generated by Django 6.0.6 on 2026-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_reseau', '0008_alter_sitereseau_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereseau',
            name='coordX',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Longitude (X)'),
        ),
        migrations.AlterField(
            model_name='sitereseau',
            name='coordY',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12, verbose_name='Latitude (Y)'),
        ),
    ]
